Use `except*` in the `cdef` functions to correctly propagate exceptions
The `cdef` functions we define in the Cython `pyx` file need to be
decorated with `except*` to properly propagate C++ exceptions that are
created within the call, otherwise the function will continue on failure
and will chain the exceptions, giving us errors like:

```
...

RuntimeError: Two entries with the same ID found!

The above exception was the direct cause of the following exception:

...

SystemError: <...> returned a result with an error set

```

Authored-by: Pablo Galindo Salgado <pgalindo3@bloomberg.net>
Reviewed-by: László Kiss Kollár <lkisskollar@bloomberg.net>
Signed-off-by: Pablo Galindo Salgado <pgalindo3@bloomberg.net>