Fix imports in exercise tests
Added empty __init__.py files to subdirectories so
they are eventually recognized as packages.
Paths have been changed to relative.

Changes are necessary for avoiding error:
ModuleNotFoundError: No module named 'exercise_(1/2/3)'.