Fix an error reported by the latest mypy
With the latest mypy, we're getting an error we didn't get before:

    error: Incompatible import of "Protocol" (imported name has type
    "type[typing_extensions._Protocol]", local name has type
    "type[typing._Protocol]")

We no longer need to use `typing_extensions` for `Protocol`, though:
we've dropped support for all Python versions that didn't have
`Protocol` in the stdlib.

Signed-off-by: Matt Wozniski <godlygeek@gmail.com>